### PR TITLE
try to fix issues 356

### PR DESCRIPTION
**Pull request by zhangyafeikimi**
Please test it carefully.
I only test it under ubuntu 16.

### CODE REVIEW

**Comment by amoffat** [comment]
@zhangyafeikimi can you make your changes to this PR please?  https://github.com/amoffat/sh/pull/362/files#diff-2c2fab1457aa782cf8f2f34ba9ae0975R132

We need `poll_select` to behave exactly like `select.select`, so we can use one or the other, depending on if the system supports `select.poll` or not.

**Comment by zhangyafeikimi** [comment]
Actually, poll_select to hardly behaves exactly like select.select. I don't  think it is the right way.
For example, the 1st and 2nd our_select are running in a while loop, an intrusive modification is better, using poll_select instead of select.select is less efficient.


As I said early, all posix OS have poll, and select has a fatal deficiency.
poll is always preferred, no need to switch between select or poll.

**Comment by zhangyafeikimi** [comment]
@amoffat 
If you insist on switch between select and poll, an intrusive modification is also better.
Don't try to expect poll_select to be equivalent to select.select.

**Comment by amoffat** [comment]
I don't think the calling code should care whether select.select or select.poll was used, that's why it's abstracted out into a separate function, poll_select.  In order for that to work though, it has to behave the same.  I don't see any reason why it shouldn't be able to behave the same.  The only problem I am interested in addressing is the file-descriptor limit with select.select, so I don't care if we are not using select.poll efficiently.

I do insist on using poll_select because it is not fully clear which systems in the wild [HAVE_BROKEN_POLL](https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Modules/selectmodule.c#L329) and I'm not interested in breaking those systems and then coming back to this problem.

**Comment by zhangyafeikimi** [comment]
Yes, "HAVE_BROKEN_POLL" makes sense.
Well, don't try to let poll be like select. They have something different in nature.
Let's make another abstract layer to adapt select or poll or epoll or others...

**Comment by amoffat** [comment]
> Let's make another abstract layer to adapt select or poll
I agree, that is what I was trying to do with `poll_select` in [this PR](https://github.com/amoffat/sh/pull/362/files).  Unfortunately I cannot merge your PR until I am confident that it will work on systems where `select.poll` is broken or unimplemented.

**Comment by zhangyafeikimi** [comment]
@amoffat Please don't merge my PR, it only uses poll.
I will try to make a abstract layer in days.

**Comment by amoffat** [comment]
Ok sounds good @zhangyafeikimi.  Reach out to me if you run into troubles.

**Comment by zhangyafeikimi** [comment]
updated

**Comment by amoffat** [comment]
good work @zhangyafeikimi.  very clean abstractions :+1: .  I merged your code into [release-1.12.10](https://github.com/amoffat/sh/pull/367/commits/8a21e8785866db612979fb84a02264ff86daf1ae) and added a formal test.  it will be merged into master shortly

**Comment by zhangyafeikimi** [comment]
See it. Thank you.

**Comment by boksic1986** [comment]
how does sh use wildcase? like 
`proc = subprocess.Popen('ls *.bc', shell=True)`

**Comment by amoffat** [comment]
@boksic1986 This isn't the correct issue for your question, but this should help http://amoffat.github.io/sh/sections/faq.html#why-doesn-t-work-as-a-command-argument

**Comment by boksic1986** [comment]
Thanks~：）



--
Chen Jiucheng

College of Animal Science , Zhejiang University

No.866 Yuhangtang RD. ,Hangzhou,  China

Tel:0571-88982308
 
From: Andrew Moffat
Date: 2017-06-19 14:53
To: amoffat/sh
CC: boksic1986; Mention
Subject: Re: [amoffat/sh] try to fix issues 356 (#364)
@boksic1986 This isn't the correct issue for your question, but this should help http://amoffat.github.io/sh/sections/faq.html#why-doesn-t-work-as-a-command-argument

**Pull request closed without merging**
