### PR TITLE
Explicitly add support for Python 3.6

### PR DESCRIPTION
**Pull request by samueldg**
- Updated the automated tests to run on Python 3.6;
- Added the version the PyPI classifiers;
- Edited the docs to indicate support up to 3.6;
- Edited a comment about inconsistent ctrl-d behavior in Python
  (tested 3.6 behaves like 3.3-3.5)

### CODE REVIEW

**Comment by samueldg** [comment]
@amoffat As you can see, one of the test is failing:
https://travis-ci.org/samueldg/sh/jobs/209206256

`FunctionalTests.test_piped_exception1` fails for "Python3.6, locale 'C', poller: poll".

I'm testing on Mac OSX though, and the tests, including this one, are all passing for Python 3.6.
I do however have weird message that Python unexpectedly shut down, which could be related (?)

**Comment by amoffat** [comment]
Thanks for reporting this @samueldg, I will try to investigate tomorrow

**Comment by amoffat** [comment]
I refreshed the build on Travis and everything looks good.  Running the tests locally on linux looks good too.  The 120 error code from the [errored build](https://travis-ci.org/samueldg/sh/jobs/209206256#L838) is interesting, and leads [here](https://bugs.python.org/issue29130).  I have seen some weirdness in the tests as well from time to time.

I will merge this regardless, since I think the problem is isolated to the tests, and cannot be reproduced consistently.

**Comment by samueldg** [comment]
Interesting! Thanks for the quick follow-up, and for the amazing lib.

**Comment by amoffat** [comment]
Thank you for helping it get to python 3.6 :+1:

**Pull request closed without merging**
