### PR TITLE
Use f-strings

### PR DESCRIPTION
**Pull request by eumiro**
Replace `%` and `.format` syntax with f-strings where appropriate. Also replace the text indentation code with stdlib's `textwrap.indent` method call.

### CODE REVIEW

**Review by amoffatgmi — APPROVED** [review]
Cool, lgtm

**Comment by amoffat** [comment]
Please don't force push @eumiro. It hides your changes and means I need to review them from the start again. Only add new commits so that the audit trail of what changed is clear.

**Comment by eumiro** [comment]
Sorry for the forcepush. I had difficulties running tests on my host, so I waited for the CI (that you had to approve). The only change I did now was the `black` reformat of one line.

In the first CI run I also saw one test fail and wanted to check it after the re-run of CI.

**Comment by ecederstrand** [comment]
@eumiro There's a single test failure in `test_change_log_message`. Can you have a look at that?

**Comment by ecederstrand** [comment]
Thanks for the contribution!

**Pull request merged**
