### PR TITLE
Fix execution contexts on the REPL

### PR DESCRIPTION
**Pull request by abadger**
This is a fix for #422 

On the REPL and from the command line, Python doesn't keep source code
in the stack frame for the toplevel.  Therefore we can't inspect it and
look for the variable being assigned to in order to remove it from
sys.modules.

This is a cornercase but we can hack around it by trying to retrieve the
variable name from the code object instead.  This depends more heavily
on Python internals but this was already code which dove into Python's
internals a bit so perhaps this is okay.

<strike>Since I needed to run the tests on Python3.7, this also includes a fix for the test suite on Python3.7</strike>  I pulled the Python-3.7 changes out to their own PR.

### CODE REVIEW

**Comment by abadger** [comment]
I'm not sure what the issue is trying to build this on pypy.  The test suite passes locally for me on pypy but I have a newer version than is running on travis:
```
$ pypy --version
Python 2.7.13 (1d8462e42c37, Aug 30 2018, 09:58:57)
[PyPy 6.0.0 with GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```
https://toshio.fedorapeople.org/sh-passing-tests-on-local-pypy.log

**Comment by abadger** [comment]
Okay, I grabbed the travis version of pypy in a VM and I found the problem.  Older versions of pypy don't report parent[1] in the same way as CPython (and newer pypy corrects it).  I'll special case that to get it to work.

**Comment by amoffat** [comment]
Great work on this @abadger and solid test :+1:.  Will go out with the next release.

**Comment by abadger** [comment]
Cool.  Thanks for merging all the outstanding PRs :-)

I noticed some sloppy coding I included in this PR.  I'll submit another PR within the hour to address that.

**Pull request merged**
